var quotes = [
	["If they would rather die they had better do it and decrease the surplus population","Scrooge (Stave 1)"],
	["Secret and self-contained, and solitary as an oyster","Narrator (Stave 1)"],
	["another idol has displaced me... a golden one","Belle (Stave 2)"],
	["odious, stingy, hard, unfeeling man","Mrs Cratchit (Stave 3)"],
	["Scrooge regarded everyone with a delighted smile","Narrator (Stave 5)"],
	["All in a glow... his eyes sparkled","Narrator (Stave 1)"],
	["I'll keep my Christmas humour to the last","Fred (Stave 1)"],
	["his offences carry their own punishment","Fred (Stave 3)"],
	["if you should happen, by any unlikely chance, to know a man more blest in a laugh than Scrooges's nephew, all I can say, I should like to know him too","Narrator (Stave 3)"],
	["Bob told them of the extraordinary kindness of Mr Scrooge's nephew","Narrator (Stave 4)"],
	["my clerk, with fifteen shillings a week, and a wife and family, talking about a merry Christmas. I'll retire a Bedlam","Scrooge (Stave 1)"],
	["went down a slide on Cornhill, at the end of a lane of boys, twenty times, in honour of its being Christmas Eve","Narrator (Stave 1)"],
	["Nobody said or thought is was a small pudding for a large family. It would have been a flat heresy to do so","Narrator (Stave 3)"],
	["He told me... it might be pleasant for them to remember upon Christmas Day, who made lame beggars walk and blind men see","Bob Cratchit (Stave 3)"],
	["Bob was very cheerful with them, and spoke pleasantly to all the family","Narrator (Stave 4)"],
	["I am here tonight to warn you","Marley's Ghost (Stave 1)"],
	["the spectre's voiced disturbed the very marrow of his bones","Narrator (Stave 1)"],
	["there was something very awful in the spectre's being provided with an infernal atmosphere of its own","Narrator (Stave 1)"],
	["I wear the chain I forged in life","Marley's Ghost (Stave 1)"],
	["Business! Mankind was my business. The common welfare was my business","Marley's Ghost (Stave 1)"],
	["From the crown of its head there sprung a bright, clear jet of light","Narrator (Stave 2)"],
	["But the relentless Ghost pinioned him in both arms, and forced him to observe","Narrator (Stave 2)"],
	["there sat a jolly Giant, glorious to see, who bore a glowing torch, in shape, not unlike Plenty's horn","Narrtor (Stave 3)"],
	["This boy is Ignorance. This girl is Want. Beware of them both","Ghost of Christmas Present (Stave 3)"],
	["Scrooge feared the silent shape so much that his legs trembled beneath him","Narrator (Stave 4)"],
	["when men and women seem by one consent to open up their shut-up hearts freely, and to think of people below them as if they really were fellow passengers to the grave","Fred (Stave 1)"],
	["A poor excuse for picking a man's pocket every twenty-fifth of December!","Scrooge (Stave 1)"],
	["Out upon merry Christmas! What good had it ever done to him?","Narrator (Stave 2)"],
	["I will honour christmas in my heart, and try to keep it all the year","Scrooge (Stave 5)"],
	["are there no prisons?... the Union Workhouses?... the Treadmill and the Poor Law are in full vigour then","Scrooge (Stave 1)"],
	["Father is so much kinder than he used to be... I was not afraid to ask him once more if you might come home","Fan (Stave 2)"],
	["said Scrooge with an interest he had never felt before, \"tell me if Tiny Tim will live\"","Scrooge (Stave 3)"],
	["Oh, tell me I may sponge away the writing on this stone!","Scrooge (Stave 4)"],
	["I am as light as a feather, I am as happy as an angel, I am as merry as a schoolboy. I am as giddy as a drunken man","Scrooge (Stave 5)"],
	["might have called him father, might have been a springtime in the haggard winter of his life, his sight grew very dim indeed","Narrator (Stave 2)"],
	["I should have liked, I do confess, to have had the lightest license of a child and yet to have been man enough to know its value","Scrooge (Stave 2)"],
	["I wouldn't show weak eyes to your father, when he comes home, for the world","Mrs Cratchit (Stave 4)"],
	["He did it all, and infinitely more; and to Tiny Tim, who did NOT die, he was a second father","Narrator (Stave 5)"],
	["The master-passion, Gain, engrosses you","Belle (Stave 2)"],
	["most of all beware this boy, for on his brow I see that written which is Doom, unless the writing be erased","Ghost of Christmas Present (Stave 3)"],
	["Alleys and archways, like so many cesspools, disgorged their offences of smell and dirt and life in the straggling streets","Narrator (Stave 4)"],
	["by the way these cranks talk, you'd think everybody has to look after everybody else, as if we're all mixed up together like bees in a hive","Mr Birling"],
	["you'll hear some people saying war is inevitable... fiddlesticks!","Mr Birling"],
	["I was an alderman for years - and Lord Mayor two years ago - and I'm still on the Bench - so I know the Brumley police officers pretty well","Mr Birling"],
	["Now look at the pair of them - the famous younger generation who know it all. And they can't even take a joke","Mr Birling"],
	["there's every excuse for what your mother and I did","Mr Birling"],
	["you know, my husband was Lord Mayor only two years ago and that he's still a magistrate","Mrs Birling"],
	["I'm very sorry but I think she only had herself to blame","Mrs Birling"],
	["As if a girl of that sort would ever refuse money","Mrs Birling"],
	["he ought to be dealt with very severely... make sure that he's compelled to confess in public his responsibility","Mrs Birling"],
	["What an expression, Sheila! Really, the things you girls pick up these days","Mrs Birling"],
	["Look - Mummy - isn't it a beauty?","Sheila Birling"],
	["I don't believe I will. (Half playful, half serious, to Gerald.) So you be careful","Sheila Birling"],
	["so you used the power you had... to punish the girl","Inspector Goole"],
	["I'll never, never do it again to anybody... I feel now I can never go there again","Sheila Birling"],
	["You began to learn something. And now you've stopped. You're ready to go on in the same old way","Sheila Birling"],
	["Why shouldn't they try for higher wages? We try for the highest possible prices","Eric Birling"],
	["I was in that state when a chap easily turns nasty - and I threatened to make a row","Eric Birling"],
	["And that's when it happened. And I don't even remember - that's the hellish thing","Eric Birling"],
	["you turned her away - yes, and you killed her - and the child she'd have too - my child... damn you, damn you","Eric Birling"],
	["(shouting) and I say that girl's dead and we all helped to kill her - and that's what matters","Eric Birling"],
	["Why should you stay? It's bound to be unpleasant and disturbing","Gerald Croft"],
	["I hate those hard-eyed dough-faced women","Gerald Croft"],
	["She was young and pretty and warm-hearted - and intensely grateful. I became at once the most important person in her life - you understand?","Gerlad Croft"],
	["I want you to understand that I didn't isntall her there so that I could make love to her... I was sorry for her... I didn't ask for anything in return","Gerald Croft"],
	["Everything's alright now Sheila. What about this ring?","Gerald"],
	["Two hours ago, a young woman died in the infirmary. She'd been taken there this afternoon because she'd swallowed a lot of strong disinfectant. Burnt her inside out, of course","Inspector Goole"],
	["It is better to ask for the Earth than to take it","Inspector Goole"],
	["Public men... have responsibilities as well as privileges","Inspector Goole"],
	["there are millions and millions of Eva Smiths and John smiths still with us, with their lives, their hopes and fears... all intertwined with our lives","Inspector Goole"],
	["If men will not learn that lesson, they will be taught it in fire and blood and anguish","Inspector Goole"],
	["She was a lively looking girl - country-bred, I fancy - and she'd been working in one of our shops for over a year. A good worker too","Mr Birling"],
	["Just used her for the end of a stupid drunken evening, as if she was an animal, a thing, not a person","Inspector Goole"],
	["Perhaps I ought to warn you that he's an old friend of mine, and that I see him fairly regularly. We play gold together sometimes up at the West Brumley","Mr Birling"],
	["She was claiming elaborate fine feelings and scruples taht were simply absurd in a girl in her position","Mrs Birling"],
	["I thought it would do us all a bit of good if sometimes we tried to put ourselves in the place of these young women","Inspector Goole"],
	["But these girls aren't cheap labour - they're people","Sheila Birling"],
	["Now you three young people, just listen to this... you'll be living in a world that'lll have forgotten all these Capital versus Labout agitators and these silly little war scares","Mr Birling"],
	["Well I don't blame you. But don't forget I'm ashamed of you as well - yes both of your","Eric Birling"],
	["You began to learn something. And now you've stopped. You're ready to go on in the same old way","Sheila Birling"],
	["You mustn't try to build up a wall between us and that girl","Sheila Birling"],
	["she had a lot to say - far too much - so she had to go","Mr Birling"],
	["we hardly ever told him anything he didn't know. Did you notice that?","Sheila Birling"],
	["The rude way he spoke to Mr Birling and me - it was quite extraordinary","Mrs Birling"],
	["We don't live alone, we are members of one body","Inspector Goole"],
	["It's my duty to keep labour costs down","Mr Birling"],
	["I used my influence to have it refused","Mrs Birling"],
];

var title = "Last Minute Quotes";