var quotes = [
	["Never forget it... remember what you did","Inspector Goole"],
	["there are millions and millions of Eva Smiths and John Smiths still with us, with their lives, their hopes and fears... all intertwined with out lives","Inspector Goole"],
	["If men will not learn that lesson, they will be taught it in fire and blood and anguish","Inspector Goole"],
	["We don't live alone, we are members of one body","Inspector Goole"],
	["But these girls aren't cheap labour - they're people","Sheila Birling"],
	["community and all that nonsense","Mr Birling"],
	["It's my duty to keep labour costs down","Mr Birling"],
	["by the way these cranks talk, you'd think everybody has to look after everybody else, as if we're all mixed up together like bees in a hive","Mr Birling"],
	["Probably a socialist or some sort of crank","Mr Birling"],
	["I used my influence to have it refused","Mrs Birling"],
	["She was claiming elaborate fine feelings and scruples that were simply absurd in a girl in her position","Mrs Birling"],
	["I'm very sorry but I think she only had herself to blame","Mrs Birling"],
	["As if a girl of that sort would ever refuse money!","Mrs Birling"],
	["Go and look for the father of the child. It's his responsibility","Mrs Birling"],
	["I went to the manager and told him this girl had been very impertinent","Sheila Birling"],
	["And if I could help her now, I would","Sheila Birling"],
	["you turned her away - yes, and you killed her - and the child she'd have had too - my child... damn you, damn you","Eric Birling"],
	["the fact remains that I did what I did","Eric Birling"],
	["Everything's all right now Sheila. What about this ring?","Gerald"],
	["She was young and pretty and warm-hearted - and intensely grateful. I became at once the most important person in her life - you understand?","Gerald Croft"],
	["Just used her for the end of a stupid drunken evening, as if she was an animal, a thing, not a person","Inspector Goole"],
];

var title = "Social Responsibility in An Inspector Calls";